-- liquibase formatted sql

-- changeset abdessalam:1
CREATE TABLE users
(
    user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name         VARCHAR(50)  NOT NULL,
    last_name          VARCHAR(50)  NOT NULL,
    username           VARCHAR(50)  NOT NULL,
    email              VARCHAR(100) NOT NULL,
    keycloak_sub       VARCHAR(100) NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    profile_picture_id VARCHAR(255),

    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_keycloak_sub UNIQUE (keycloak_sub)
    );

-- rollback DROP TABLE users;

-- changeset abdessalam:2
CREATE INDEX idx_user_name ON users (username);
--
-- -- rollback DROP INDEX IF EXISTS idx_user_name;
