-- liquibase formatted sql

-- changeset abdessalam:1
CREATE TABLE club
(
    club_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_name          VARCHAR(100) NOT NULL,
    club_full_name     VARCHAR(200),
    description        VARCHAR(1000),
    profile_picture_id VARCHAR(255),

    CONSTRAINT uq_club_name UNIQUE (club_name)
);

-- rollback DROP TABLE club;

-- changeset abdessalam:2
CREATE INDEX idx_club_name ON club (club_name);

-- rollback DROP INDEX IF EXISTS idx_club_name;