-- liquibase formatted sql

-- changeset abdessalam:1
CREATE TABLE join_request
(
    join_request_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    join_request_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    join_request_status VARCHAR(20) NOT NULL,
    user_id             BIGINT      NOT NULL,
    club_id             BIGINT      NOT NULL,

    CONSTRAINT fk_join_request_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_join_request_club FOREIGN KEY (club_id) REFERENCES club (club_id) ON DELETE CASCADE
);

-- rollback DROP TABLE join_request;

-- changeset abdessalam:2
CREATE INDEX idx_join_request_user_id ON join_request (user_id);
CREATE INDEX idx_join_request_club_id ON join_request (club_id);

-- rollback DROP INDEX IF EXISTS idx_join_request_club_id;
-- rollback DROP INDEX IF EXISTS idx_join_request_user_id;