-- liquibase formatted sql

-- changeset abdessalam:1
CREATE TABLE club_membership
(
    membership_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_role        VARCHAR(30) NOT NULL,
    role_title       VARCHAR(100),
    role_description VARCHAR(255),
    started_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id          BIGINT      NOT NULL,
    club_id          BIGINT      NOT NULL,

    CONSTRAINT fk_membership_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_membership_club FOREIGN KEY (club_id) REFERENCES club (club_id) ON DELETE CASCADE,

    CONSTRAINT uq_user_club_membership UNIQUE (user_id, club_id)
);

-- rollback DROP TABLE club_membership;

-- changeset abdessalam:2
CREATE INDEX idx_membership_user_id ON club_membership (user_id);
CREATE INDEX idx_membership_club_id ON club_membership (club_id);
CREATE INDEX idx_membership_role ON club_membership (club_role);

-- rollback DROP INDEX IF EXISTS idx_membership_role;
-- rollback DROP INDEX IF EXISTS idx_membership_club_id;
-- rollback DROP INDEX IF EXISTS idx_membership_user_id;