-- liquibase formatted sql

-- changeset abdessalam:1
CREATE TABLE assistant_member_privilege
(
    privilege_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    privilege     VARCHAR(50) NOT NULL,
    granted_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    membership_id BIGINT      NOT NULL,

    CONSTRAINT fk_privilege_membership FOREIGN KEY (membership_id) REFERENCES club_membership (membership_id) ON DELETE CASCADE

);

-- rollback DROP TABLE assistant_member_privilege;

-- changeset abdessalam:2
CREATE INDEX idx_privilege_membership_id ON assistant_member_privilege (membership_id);

-- rollback DROP INDEX IF EXISTS idx_privilege_membership_id;