-- liquibase formatted sql

-- changeset abdessalam:1
CREATE TABLE profile_picture
(
    profile_picture_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s3_key             VARCHAR(500) NOT NULL
);

-- rollback DROP TABLE profile_picture;