-- liquibase formatted sql

-- changeset abdessalam:1
CREATE TABLE post
(
    post_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    visibility  VARCHAR(20)  NOT NULL,
    club_id     BIGINT       NOT NULL,

    CONSTRAINT fk_post_club FOREIGN KEY (club_id) REFERENCES club (club_id) ON DELETE CASCADE
);

-- rollback DROP TABLE post;

-- changeset abdessalam:2
CREATE INDEX idx_post_club_id ON post (club_id);
CREATE INDEX idx_post_visibility ON post (visibility);

-- rollback DROP INDEX IF EXISTS idx_post_visibility;
-- rollback DROP INDEX IF EXISTS idx_post_club_id;