-- liquibase formatted sql

-- changeset abdessalam:1
CREATE TABLE attachment
(
    attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type          VARCHAR(20)  NOT NULL,
    s3_key        VARCHAR(500) NOT NULL
);

-- rollback DROP TABLE attachment;