-- liquibase formatted sql

-- changeset abdessalam:1
CREATE TABLE event
(
    event_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    visibility  VARCHAR(20)  NOT NULL,
    start_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    club_id     BIGINT       NOT NULL,

    CONSTRAINT fk_event_club FOREIGN KEY (club_id) REFERENCES club (club_id) ON DELETE CASCADE
);

-- rollback DROP TABLE event;

-- changeset abdessalam:2
CREATE INDEX idx_event_club_id ON event (club_id);
CREATE INDEX idx_event_visibility ON event (visibility);
CREATE INDEX idx_event_dates ON event (start_date, end_date);

-- rollback DROP INDEX IF EXISTS idx_event_dates;
-- rollback DROP INDEX IF EXISTS idx_event_visibility;
-- rollback DROP INDEX IF EXISTS idx_event_club_id;