-- liquibase formatted sql

-- changeset abdessalam:1
CREATE TABLE comment
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id    BIGINT        NOT NULL,

    CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

-- rollback DROP TABLE comment;

-- changeset abdessalam:2
CREATE INDEX idx_comment_user_id ON comment (user_id);

-- rollback DROP INDEX IF EXISTS idx_comment_user_id;