-- liquibase formatted sql

-- changeset abdessalam:1
CREATE TABLE location
(
    location_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label         VARCHAR(100) NOT NULL,
    type VARCHAR(50)  NOT NULL
);

-- rollback DROP TABLE location;

-- changeset abdessalam:2
CREATE INDEX idx_location_type ON location (type);

-- rollback DROP INDEX IF EXISTS idx_location_type;