-- liquibase formatted sql

-- changeset abdessalam:1
CREATE TABLE location_reservation
(
    location_reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date              TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date                TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status                  VARCHAR(20)                 NOT NULL,
    event_id                BIGINT                      NOT NULL,
    location_id             BIGINT                      NOT NULL,

    CONSTRAINT fk_lr_event FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE,
    CONSTRAINT fk_lr_location FOREIGN KEY (location_id) REFERENCES location (location_id) ON DELETE CASCADE
);

-- rollback DROP TABLE location_reservation;

-- changeset abdessalam:2
CREATE INDEX idx_lr_event_id ON location_reservation (event_id);
CREATE INDEX idx_lr_location_id ON location_reservation (location_id);
CREATE INDEX idx_lr_status ON location_reservation (status);
CREATE INDEX idx_lr_dates ON location_reservation (start_date, end_date);

-- rollback DROP INDEX IF EXISTS idx_lr_dates;
-- rollback DROP INDEX IF EXISTS idx_lr_status;
-- rollback DROP INDEX IF EXISTS idx_lr_location_id;
-- rollback DROP INDEX IF EXISTS idx_lr_event_id;