-- liquibase formatted sql

-- changeset abdessalam:1
CREATE TABLE club_membership_history
(
    club_membership_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_role                  VARCHAR(30)                 NOT NULL,
    role_description           VARCHAR(255),
    role_title                 VARCHAR(100),
    started_at                 TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ended_at                   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id                    BIGINT                      NOT NULL,
    club_id                    BIGINT                      NOT NULL,

    CONSTRAINT fk_cmh_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_cmh_club FOREIGN KEY (club_id) REFERENCES club (club_id) ON DELETE CASCADE
);

-- rollback DROP TABLE club_membership_history;

-- changeset abdessalam:2
CREATE INDEX idx_cmh_user_id ON club_membership_history (user_id);
CREATE INDEX idx_cmh_club_id ON club_membership_history (club_id);

-- rollback DROP INDEX IF EXISTS idx_cmh_club_id;
-- rollback DROP INDEX IF EXISTS idx_cmh_user_id;