-- liquibase formatted sql

-- changeset tawfiq_akdir:1
CREATE TABLE endpoint
(
    endpoint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    category    VARCHAR(50)  NOT NULL,
    privileged  BOOLEAN      NOT NULL,

    CONSTRAINT uq_endpoint_name UNIQUE (name)
);

-- rollback DROP TABLE endpoint;

-- changeset tawfiq_akdir:2
CREATE INDEX idx_endpoint_category ON endpoint (category);

-- rollback DROP INDEX IF EXISTS idx_endpoint_category;
