-- liquibase formatted sql

-- changeset tawfiq_akdir:1
CREATE TABLE club_profile
(
    club_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)                NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    club_id         BIGINT                      NOT NULL,

    CONSTRAINT fk_club_profile_club FOREIGN KEY (club_id) REFERENCES club (club_id) ON DELETE CASCADE
);

-- rollback DROP TABLE club_profile;

-- changeset tawfiq_akdir:2
CREATE INDEX idx_club_profile_club_id ON club_profile (club_id);

-- rollback DROP INDEX IF EXISTS idx_club_profile_club_id;
