-- liquibase formatted sql

-- changeset tawfiq_akdir:1
CREATE TABLE club_membership_endpoint
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id BIGINT                      NOT NULL,
    endpoint_id   BIGINT                      NOT NULL,
    granted_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_cme_membership FOREIGN KEY (membership_id)
        REFERENCES club_membership (membership_id) ON DELETE CASCADE,
    CONSTRAINT fk_cme_endpoint FOREIGN KEY (endpoint_id)
        REFERENCES endpoint (endpoint_id),
    CONSTRAINT uq_cme_membership_endpoint UNIQUE (membership_id, endpoint_id)
);

-- rollback DROP TABLE club_membership_endpoint;

-- changeset tawfiq_akdir:3
CREATE INDEX idx_cme_membership_id ON club_membership_endpoint (membership_id);
CREATE INDEX idx_cme_endpoint_id ON club_membership_endpoint (endpoint_id);

-- rollback DROP INDEX IF EXISTS idx_cme_membership_id;
-- rollback DROP INDEX IF EXISTS idx_cme_endpoint_id;
