-- liquibase formatted sql

-- changeset tawfiq_akdir:1
CREATE TABLE role_grant
(
    role_grant_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_profile_id               BIGINT,
    assistant_member_privilege_id BIGINT NOT NULL,

    CONSTRAINT fk_rg_profile FOREIGN KEY (club_profile_id) REFERENCES club_profile (club_profile_id) ON DELETE SET NULL,
    CONSTRAINT fk_rg_grant FOREIGN KEY (assistant_member_privilege_id) REFERENCES assistant_member_privilege (privilege_id) ON DELETE CASCADE
);

-- rollback DROP TABLE role_grant;

-- changeset tawfiq_akdir:2
CREATE INDEX idx_rg_profile_id ON role_grant (club_profile_id);
CREATE INDEX idx_rg_grant_id ON role_grant (assistant_member_privilege_id);

-- rollback DROP INDEX IF EXISTS idx_rg_grant_id;
-- rollback DROP INDEX IF EXISTS idx_rg_profile_id;
