-- liquibase formatted sql

-- changeset tawfiq_akdir:1
CREATE TABLE club_membership_profile
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id   BIGINT                      NOT NULL,
    club_profile_id BIGINT                      NOT NULL,
    assigned_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_cmp_membership FOREIGN KEY (membership_id) REFERENCES club_membership (membership_id) ON DELETE CASCADE,
    CONSTRAINT fk_cmp_profile FOREIGN KEY (club_profile_id) REFERENCES club_profile (club_profile_id) ON DELETE CASCADE
);

-- rollback DROP TABLE club_membership_profile;

-- changeset tawfiq_akdir:2
CREATE INDEX idx_cmp_membership_id ON club_membership_profile (membership_id);
CREATE INDEX idx_cmp_profile_id ON club_membership_profile (club_profile_id);

-- rollback DROP INDEX IF EXISTS idx_cmp_profile_id;
-- rollback DROP INDEX IF EXISTS idx_cmp_membership_id;
