# loading the .env variables
spring.config.import=optional:file:.env[.properties]

spring.application.name=club_management_system

# profile
spring.profiles.active=Test

# database configuration
spring.datasource.url=jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}

# hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# S3 service
cloud.aws.credentials.access-key=${S3_BACK_END_ACCESS_KEY}
cloud.aws.credentials.secret-key=${S3_BACK_END_SECRET_KEY}
cloud.aws.region.static=us-east-1
cloud.aws.s3.endpoint=${S3_ENDPOINT_URL}
cloud.aws.s3.path-style-access-enabled=true
cloud.aws.s3.bucket=apps-build-school-clubs-management-system-bucket
